apiVersion: v1
kind: Service
metadata:
  name: clock-work-service
spec:
  selector:
    app: clock-work
  ports:
    - name: uvicorn
      protocol: TCP
      port: 8012
      targetPort: 8012
      nodePort: 32012
    - name: celery-flower
      protocol: TCP
      port: 8051
      targetPort: 8051
      nodePort: 32051
  type: NodePort
