"""
Django settings for clock_work project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import subprocess
import ipaddress
from decouple import config

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
import django
from django.db.models.signals import pre_init

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Custom ALLOWED_HOSTS class to support Kubernetes pod network subnet validation
class AllowedHostsWithSubnet(list):
    """
    Custom ALLOWED_HOSTS that supports CIDR subnet notation for Kubernetes pod networks.
    Example: Add '10.42.0.0/16' to allow all pod IPs in the 10.42.x.x range.
    """
    def __init__(self, hosts):
        self.hosts = []
        self.networks = []
        for host in hosts:
            if '/' in host:  # CIDR notation
                try:
                    self.networks.append(ipaddress.ip_network(host, strict=False))
                except ValueError:
                    pass  # Invalid CIDR, skip it
            else:
                self.hosts.append(host)
        super().__init__(self.hosts)
    
    def __contains__(self, key):
        # First check standard hosts (domains, IPs, wildcards)
        if super().__contains__(key):
            return True
        
        # Extract just the hostname/IP if port is included
        if ':' in key:
            key = key.split(':')[0]
        
        # Check if it's an IP address in any of our allowed networks
        try:
            ip = ipaddress.ip_address(key)
            for network in self.networks:
                if ip in network:
                    return True
        except ValueError:
            pass  # Not a valid IP, continue with standard checking
        
        return False


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/
# ============================ENV VARIABLES=====================================
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)
# Use custom class to support Kubernetes pod network subnets (10.42.0.0/16)
ALLOWED_HOSTS = AllowedHostsWithSubnet(config('ALLOWED_HOSTS').split(' '))
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
BUCKET_TYPE = config('BUCKET_TYPE')

DATABASE_URL = config('DATABASE_URL')
REDIS_CLOUD_URL = config('REDIS_CLOUD_URL')

MAIL_JET_API_KEY = config('MAIL_JET_API_KEY')
MAIL_JET_API_SECRET = config('MAIL_JET_API_SECRET')
MAIL_JET_EMAIL_ADDRESS = config('MAIL_JET_EMAIL_ADDRESS')
MY_EMAIL_ADDRESS = config('MY_EMAIL_ADDRESS')

# Domain and Protocol Configuration
if DEBUG:
    DOMAIN = config('DOMAIN', default='localhost:8012')
    PROTOCOL = config('PROTOCOL', default='http')
else:
    DOMAIN = config('DOMAIN')
    PROTOCOL = config('PROTOCOL')

SENTRY_AUTH_TOKEN = config('SENTRY_AUTH_TOKEN', default='')
SENTRY_ORG = config('SENTRY_ORG', default='')
SENTRY_PROJECT = config('SENTRY_PROJECT', default='')
SENTRY_ENVIRONMENT = config('SENTRY_ENVIRONMENT')  # production Or "staging", "development", etc.
SENTRY_DSH_URL = config('SENTRY_DSH_URL')

# Harbor Configuration
HARBOR_URL = config('HARBOR_URL', default='https://harbor.arpansahu.space')
HARBOR_USERNAME = config('HARBOR_USERNAME', default='admin')
HARBOR_PASSWORD = config('HARBOR_PASSWORD', default='')

PROJECT_NAME = 'clock_work'
USE_S3 = config('USE_S3', default=True, cast=bool)
# ===============================================================================


# Application definition

INSTALLED_APPS = [
    "daphne",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'clock_work',
    'account',
    'tasks',
    'celery_progress',
    'django_celery_beat',
    'django_celery_results',
    'send_email_app',
    'notifications_app',
    'check_service_health',
    'storages',  # django-storages for S3/MinIO storage
    'django_test_enforcer',  # Test coverage enforcement
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'clock_work.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'clock_work.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': config('DB_NAME'),
#         'USER': config('DB_USER'),
#         'PASSWORD': config('DB_PASSWORD'),
#         'HOST': config('DB_HOST'),
#         'PORT': config('DB_PORT'),
#     }
# }

# Parse database configuration from $DATABASE_URL
import dj_database_url
# DATABASES['default'] =  dj_database_url.config()
#updated
DATABASES = {'default': dj_database_url.config(default=config('DATABASE_URL'))}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Security Settings for Production
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_PRELOAD = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# REFERRER POLICY
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Storage Configuration
if not USE_S3:
    STATIC_URL = '/static/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    MEDIA_URL = '/media/'
else:
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='eu-north-1')
    
    # Common S3 settings
    AWS_S3_FILE_OVERWRITE = False  # Prevent overwriting files with the same name
    AWS_DEFAULT_ACL = None  # Ensure files are not public by default
    
    # Switch between MinIO and AWS S3
    if BUCKET_TYPE == 'MINIO':
        # MinIO/S3 Configuration
        AWS_QUERYSTRING_AUTH = False  # Don't add query parameters to URLs (use bucket policy instead)
        AWS_S3_SIGNATURE_VERSION = 's3v4'
        AWS_S3_USE_SSL = True
        AWS_S3_VERIFY = True
        AWS_S3_ADDRESSING_STYLE = 'path'  # Use path-style addressing for MinIO
        
        # MinIO API endpoint through nginx proxy (for upload/management operations)
        AWS_S3_ENDPOINT_URL = 'https://minioapi.arpansahu.space'
        
        # Custom domain for serving files (use API endpoint, not console)
        AWS_S3_CUSTOM_DOMAIN = f'minioapi.arpansahu.space/{AWS_STORAGE_BUCKET_NAME}'
    elif BUCKET_TYPE == 'AWS':
        AWS_S3_ENDPOINT_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
        AWS_S3_CUSTOM_DOMAIN = AWS_S3_ENDPOINT_URL
    elif BUCKET_TYPE == 'BLACKBLAZE':
        AWS_S3_REGION_NAME = 'us-east-005'
        AWS_S3_ENDPOINT = f's3.{AWS_S3_REGION_NAME}.backblazeb2.com'
        AWS_S3_ENDPOINT_URL = f'https://{AWS_S3_ENDPOINT}'
        AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.backblazeb2.com'

    # Static and Media File Storage Settings
    AWS_STATIC_LOCATION = f'portfolio/{PROJECT_NAME}/static'
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_STATIC_LOCATION}/'
    
    AWS_PUBLIC_MEDIA_LOCATION = f'portfolio/{PROJECT_NAME}/media'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_PUBLIC_MEDIA_LOCATION}/'
    
    AWS_PROTECTED_MEDIA_LOCATION = f'portfolio/{PROJECT_NAME}/protected'
    
    AWS_PRIVATE_MEDIA_LOCATION = f'portfolio/{PROJECT_NAME}/private'

    # Use your custom storage classes with modern STORAGES dict
    STORAGES = {
        'default': {
            'BACKEND': f'{PROJECT_NAME}.storage_backends.PublicMediaStorage',
            'OPTIONS': {
                'location': AWS_PUBLIC_MEDIA_LOCATION,
                'bucket_name': AWS_STORAGE_BUCKET_NAME,
                'endpoint_url': AWS_S3_ENDPOINT_URL,
                'access_key': AWS_ACCESS_KEY_ID,
                'secret_key': AWS_SECRET_ACCESS_KEY,
            },
        },
        'staticfiles': {
            'BACKEND': f'{PROJECT_NAME}.storage_backends.StaticStorage',
            'OPTIONS': {
                'location': AWS_STATIC_LOCATION,
                'bucket_name': AWS_STORAGE_BUCKET_NAME,
                'endpoint_url': AWS_S3_ENDPOINT_URL,
                'access_key': AWS_ACCESS_KEY_ID,
                'secret_key': AWS_SECRET_ACCESS_KEY,
            },
        },
        'private': {
            'BACKEND': f'{PROJECT_NAME}.storage_backends.PrivateMediaStorage',
            'OPTIONS': {
                'location': AWS_PRIVATE_MEDIA_LOCATION,
                'bucket_name': AWS_STORAGE_BUCKET_NAME,
                'endpoint_url': AWS_S3_ENDPOINT_URL,
                'access_key': AWS_ACCESS_KEY_ID,
                'secret_key': AWS_SECRET_ACCESS_KEY,
                'default_acl': 'private',
                'custom_domain': False,  # Disable custom domain for private files
            },
        },
    }

# Development settings (for local media/static handling)

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static"), ]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CELERY STUFF
CELERY_BROKER_URL = REDIS_CLOUD_URL
CELERY_RESULT_BACKEND = REDIS_CLOUD_URL
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'
CELERY_TASK_DEFAULT_QUEUE = 'clock_work_queue'

# CELERY BEAT

CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'


try:
    import channels
except ImportError:
    pass
else:
    INSTALLED_APPS.insert(0, 'channels')
    INSTALLED_APPS.append('celery_progress.websockets')

    ASGI_APPLICATION = 'clock_work.routing.application'

    CHANNEL_LAYERS = {
        'default': {
            # This example is assuming you use redis, in which case `channels_redis` is another dependency.
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [REDIS_CLOUD_URL],
            },
        },
    }

#Caching
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_CLOUD_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': PROJECT_NAME
    }
} 

# Get the current git commit hash
def get_git_commit_hash():
    try:
        return subprocess.check_output(['git', 'rev-parse', 'HEAD']).decode('utf-8').strip()
    except Exception:
        return None


# Sentry Configuration - Only initialize if DSN is provided
if SENTRY_DSH_URL and SENTRY_DSH_URL.strip():
    sentry_sdk.init(
        dsn=SENTRY_DSH_URL,
        integrations=[
                DjangoIntegration(
                    transaction_style='url',
                    middleware_spans=True,
                    # signals_spans=True,
                    # signals_denylist=[
                    #     django.db.models.signals.pre_init,
                    #     django.db.models.signals.post_init,
                    # ],
                    # cache_spans=False,
                ),
            ],
        traces_sample_rate=1.0,  # Adjust this according to your needs
        send_default_pii=True,  # To capture personal identifiable information (optional)
        release=get_git_commit_hash(),  # Set the release to the current git commit hash
    environment=SENTRY_ENVIRONMENT,  # Or "staging", "development", etc.
    # profiles_sample_rate=1.0,
)
else:
    print("⚠️  Sentry DSN not configured - Sentry monitoring disabled")

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
        'sentry': {
            'level': 'ERROR',  # Change this to WARNING or INFO if needed
            'class': 'sentry_sdk.integrations.logging.EventHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'sentry'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'sentry'],
            'level': 'ERROR',  # Only log errors to Sentry
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console', 'sentry'],
            'level': 'ERROR',  # Only log errors to Sentry
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'sentry'],
            'level': 'WARNING',  # You can set this to INFO or DEBUG as needed
            'propagate': False,
        },
        # You can add more loggers here if needed
    },
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
    },
}

# Django Test Enforcer Configuration
DJANGO_TEST_ENFORCER = {
    'enabled': True,
    'coverage_threshold': 80,
    'fail_under': False,  # Set to True to fail CI if below threshold
    'exclude_apps': [
        'django.contrib.*',
    ],
    'exclude_patterns': [
        'migrations/*',
        'admin.py',
    ],
    'include_class_based_views': True,
    'include_function_views': True,
    'include_ui_elements': True,  # Enable UI element detection
    'generate_ui_tests': True,  # Enable UI test generation
    'test_output_location': 'app',  # 'app' (default), 'folder', or 'both'
}

# CSRF Trusted Origins - dynamically constructed from environment variables
# Supports both the main domain and all subdomains (wildcard)
CSRF_TRUSTED_ORIGINS = [f'{PROTOCOL}://{DOMAIN}', f'{PROTOCOL}://*.{DOMAIN}']